server:
  port: 5555
name: parking-lot-service

spring:
  cloud:
    stream:
      bindings:
        input: profiles

eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_CLIENT_SERVICE_URL_DEFAULTZONE:http://localhost:8761/eureka}
  instance:
    prefer-ip-address: true
    leaseRenewalIntervalInSeconds: 1
    leaseExpirationDurationInSeconds: 2

ribbon:
  eureka:
    enabled: true
    ReadTimeout: 20000
    connectTimeout: 20000

feign:
  hystrix:
    enabled: true

management.security.enabled: false