server:
  port: 8765
  context-path: /zuul-service
name: zuul-service

spring:
  sleuth:
    sampler.percentage: 1.0
  zipkin:
    baseUrl: http://ZIPKIN-SERVICE/
    locator.discovery.enabled: true

eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_CLIENT_SERVICE_URL_DEFAULTZONE:http://localhost:8761/eureka}
  instance:
    prefer-ip-address: true
    health-check-url-path: ${server.context-path}/health
    status-page-url-path: ${server.context-path}/info
    leaseRenewalIntervalInSeconds: 1
    leaseExpirationDurationInSeconds: 2

ribbon:
  eureka:
    enabled: true
    ReadTimeout: 20000
    connectTimeout: 20000

zuul:
  ignoredServices: "*"
  routes:
    parkinglotservice:
      path: /parking-lot-service/api/parking-lot/**
      serviceId: parking-lot-service
      stripPrefix: false
    excelexportservice:
      path: /excel-export-service/api/parking-lot/**
      serviceId: excel-export-service
      stripPrefix: false
    parkingspotwebapp:
      path: /parking-spot-for-me-webapp/**
      serviceId: parking-spot-for-me-webapp
    parkinglotservicedoc:
      path: /parking-lot/**
      serviceId: parking-lot-service
    excelexportservicedoc:
      path: /excel-export/**
      serviceId: excel-export-service

management.security.enabled: false